services:
  django:
    container_name: twitter-clone-django
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: twitter-clone-postgres
    image: postgres:16
    volumes:
      - ./db:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  react:
    container_name: twitter-clone-react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/code
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    command: npm start

volumes:
  db:
